### ISSUE TITLE
bumpr getting GitHub API errors

### ISSUE THREAD

**Issue by cardonator** [haya14busa/action-bumpr#34]
starting today we've been seeing this error coming back from bumpr for some reason.
```
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/issues#create-an-issue-comment"
}
```
This is causing our bump job to fail to post a comment on the issue with the new version.

Our release job is also getting a weird error I can't explain
```
jq: error (at <stdin>:4): Cannot index string with string "merge_commit_sha"
```

Any idea what is happening here? Our job has been working perfectly for two years now until today.

**Comment by cardonator** [comment]
Sorry, I just realized a configuration change was made on our organization that could have caused this. I'll look into that and open a new issue if it doesn't resolve it.

**Comment by jcarpenter12** [comment]
@cardonator I am also facing this issue, did you find out the cause out of interest?

**Comment by cardonator** [comment]
> @cardonator I am also facing this issue, did you find out the cause out of interest?

The issue was that the GitHub Actions configuration was set so it couldn't write to repos. This is in your Settings under Actions->General->Workflow Permissions.
