### ISSUE TITLE
Latest version not working

### ISSUE THREAD

**Issue by assil-ingka** [haya14busa/action-bumpr#37]
Latest version throws following error:

```
 * [new tag]         v0.0.1     -> v0.0.1
/entrypoint.sh: line 146: can't create : nonexistent directory
```

This doesnt work:

`echo "current_version=${CURRENT_VERSION}" >> "$GITHUB_OUTPUT"`

**Comment by shogo82148** [comment]
What version is your runner?
2.297.0 or greater is required

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by assil-ingka** [comment]
Thank you, that seems to be the reason! Didnt expect a minor release to break compatibility
